# Generated by Django 5.1.4 on 2024-12-27 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20241216_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
