# Generated by Django 5.1.4 on 2024-12-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('postal_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('Created', 'Criado'), ('Processing', 'Processando'), ('Completed', 'Completo'), ('Shipped', 'Enviado'), ('Ready for pickup', 'Pronto para retirada'), ('Canceled', 'Cancelado')], default='Created', max_length=20, verbose_name='Status')),
                ('transport', models.CharField(choices=[('Moto taxi', 'Moto táxi'), ('Recipient pickup', 'Retirada no local')], default='Moto taxi', max_length=20, verbose_name='Transporte')),
                ('transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço do transporte')),
                ('note', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='listings.product')),
            ],
        ),
    ]
