# Generated by Django 5.1.4 on 2025-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.CharField(choices=[('Home delivery', 'Entrega ao domicílio'), ('Recipient pickup', 'Retirada no local')], default='Home delivery', max_length=20, verbose_name='Transporte'),
        ),
    ]
