# Generated by Django 5.1.4 on 2025-01-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('dinheiro', 'Dinheiro'), ('visa', 'Visa')], default='mpesa', max_length=20, verbose_name='Métodos de pagemento'),
            preserve_default=False,
        ),
    ]
